### ISSUE TITLE
Companion app 

### ISSUE THREAD

**Issue by Cybsjan** [rm2kdev/foundry-dnd-beyond-rolls-module#6]
Hi! 

First up, the module works! And that's great. Another module for passing dndbeyond rolls to foundry seems to have issues when also having the beyond20 extension installed. Something I have because I also play some games on roll20. Its great that your module sidesteps that issues. 

One thing I dislike is having to run the companion app when I want to run this module. It's another thing running and one thing I'm not sure (with my little computer knowledge) of is how much risk is involved. Is it another thing that opens up my pc to the web or not? 
I'm not sure if there's another way to get the rolls from dndbeyond in foundry without having someone hosting somethign somewhere, making it cost money instead of it being free. So I think that might be the reasoning for this companion app.

**Comment by rm2kdev** [comment]
Just a quick answer as im working right now.
1, it opens a port up on your computer to communicate however it does not open the port to the internet you do that in your firewall in your modem.

2, thats exactly why you have to run the companion, something somewhere needs to be connecting to DDB and the foundry client can't due to browser restrictions (foundry is a cleverly hidden web browser) so if you want it to be free you have to run a companion until DDB opens up the apis for third party use (which they likely won't ever as they're working on their own VTT's)

**Comment by Cybsjan** [comment]
Gotcha, thanks for the explanation :D
